### ISSUE TITLE
x86_64 compatibility?

### ISSUE THREAD

**Issue by CodeTalker625** [Therdel/cssHack#3]
Could not compile using a 64-bit Ubuntu system but was able to compile successfully using a 32-bit debian 11 system. However, when I copied the "libcsHack.so" file to my 64-bit Ubuntu system and tried to use the "css_with_hack.bash" script, it wouldn't work. Got a "wrong ELF class: ELFCLASS32" error message. My guess is because it was compiled for a 32bit system. Is it possible to compile the project to be run in a 64-bit system? If yes, what do I have to change in the CMakeLists.txt and/or source files? Thanks!

**Comment by Therdel** [comment]
It's a forced 32-bit build on GNU/Linux, yes, it also says so in the [CMakeLists.txt](https://github.com/Therdel/cssHack/blob/90b391218e71142c524f6c8e3bab42c424682e63/CMakeLists.txt#L138-L142)

The reason is that the hl2_linux executable used to be 32-bit, which needs a 32-bit library AFAIK:
```
 ~$ file ~/.local/share/Steam/steamapps/common/Counter-Strike\ Source/hl2_linux 
/home/*****/.local/share/Steam/steamapps/common/Counter-Strike Source/hl2_linux: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 3.2.32, BuildID[sha1]=45233e883b71c05725159bfffcee53e0a7d66ad3, not stripped
```
If that situation is different for a more up-to-date Ubuntu, you'd have to do more than just changing the target architecture to 64 bits.

I have unconditionally linked to the 32-bit versions of libSDL and libGL, [here](https://github.com/Therdel/cssHack/blob/90b391218e71142c524f6c8e3bab42c424682e63/CMakeLists.txt#L74) and [here](https://github.com/Therdel/cssHack/blob/90b391218e71142c524f6c8e3bab42c424682e63/CMakeLists.txt#L111) - which would be a problem.

Also, while I do remember I have used `uintptr_t` for storing addresses throughout my code (which automatically resizes to 32/64 bit depending on build),
first thing off the top of my head that should break on 64 bit is the DetourToCallback code, which uses the 32bit instructions for patching [here at least](https://github.com/Therdel/cssHack/blob/90b391218e71142c524f6c8e3bab42c424682e63/src/DetourToCallback.hpp#L13-L45) for saving registers before executing the "inserted" callback.
I think the detouring would have to be reworked for 64-bit, either way. [The "naked" Detour code implicitly uses non-64 bit instructions for jumping around currently, too](https://github.com/Therdel/cssHack/blob/90b391218e71142c524f6c8e3bab42c424682e63/src/Detour.cpp#L127).
But I expect there to be more examples.

It's an interesting job, I think! Feel free to experiment and submit pull requests.

**Comment by Therdel** [comment]
The executable seems to be 32-bit on up to date 64-bit Ubuntu 20.04, too.
I can't see a reason why you would want to build a 64-bit version of the hack, then
```
*****:~$ uname -a
Linux ***** 5.13.0-30-generic #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
*****:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
*****:~$ file .local/share/Steam/steamapps/common/Counter-Strike\ Source/hl2_linux 
.local/share/Steam/steamapps/common/Counter-Strike Source/hl2_linux: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 3.2.32, BuildID[sha1]=45233e883b71c05725159bfffcee53e0a7d66ad3, not stripped
*****:~$ file /bin/ls
/bin/ls: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=2f15ad836be3339dec0e2e6a3c637e08e48aacbd, for GNU/Linux 3.2.0, stripped
```

**Comment by schmerto** [comment]
> I can't see a reason why you would want to build a 64-bit version of the hack

To play online through Steam.    (as far as I know you can not run Steam on 32 bit).

I am a complete noob with linux, I just really fell in love with your work and this is the only reason why I started using linux so I hope to run ur work in one day

**Comment by Therdel** [comment]
The hl2 executable is 32 bit, the steam executable is unrelated. (You're injecting into the wrong process I think)

Also - the project really is not in a runnable state. I suggest you check out [mince](https://github.com/Therdel/mince), my new game hacking experiment written in rust. Cleaner and more understandable - you can translate the functionality you need from this project as a learning experience!

**Comment by schmerto** [comment]
I was successfully compiled ur work and I am also already aware of the injection method by @aixxe, (I injected his simple work on 64 bit)

but how to run hl2_linux on a 32 bit linux system?  I can't find the method for 3 days how to run Steam on a 32 bit linux system.

**Comment by Therdel** [comment]
Please read my past messages, I answered this on Feb 28, 2022.
I ran and injected into 32bit cs:s (hl2_linux) on 64bit ubuntu (and 64bit windows, for that matter).
I haven't experimented on 32bit operating systems.
